#!/bin/bash
#
# copy default user profile
#
# 11.07.2009
# Jörg Richter/Thomas Schmitt
#

# source settings
. /etc/linuxmuster-client.conf || exit 1
. /usr/share/linuxmuster-client/config || exit 1
. /usr/share/linuxmuster-client/helperfunctions.sh || exit 1

# quit if TEMPLATE_USER is not set
[ -z "$TEMPLATE_USER" ] && exit 0

# get home of template user
PROFILE_HOME=$(getent passwd $TEMPLATE_USER | awk -F\: '{ print $6 }')

# create basedir for application settings if necessary
[ -d $HOME/$APPS_BASEDIR ] || mkdir -p $HOME/$APPS_BASEDIR

# process firefox profile if requested
if [ "$FIREFOX" = "yes" ]; then

	# create default firefox profile dir if necessary
	[ -d $HOME/.mozilla/firefox ] || mkdir -p $HOME/.mozilla/firefox

	# create profiles.ini with path to custom profile directory
	echo -e "[General]\nStartWithLastProfile=1\n\n[Profile0]\nName=firefox\nIsRelative=1\nPath=../../$APPS_BASEDIR/$FIREFOX_PROFILE\nDefault=1\n\n" > $HOME/.mozilla/firefox/profiles.ini
	chown -R $USER $HOME/.mozilla

	# create custom firefox profile directory
	if [ ! -d $HOME/$APPS_BASEDIR/$FIREFOX_PROFILE ]; then

		# skip this if user is template user
		if [ "$USER" != "$TEMPLATE_USER" ]; then
			[ -e "$PROFILE_HOME/$APPS_BASEDIR/$FIREFOX_PROFILE" ] && cp -a $PROFILE_HOME/$APPS_BASEDIR/$FIREFOX_PROFILE $HOME/$APPS_BASEDIR
		fi

		# create it if it was not copied
		[ -d $HOME/$APPS_BASEDIR/$FIREFOX_PROFILE ] || mkdir $HOME/$APPS_BASEDIR/$FIREFOX_PROFILE

	fi

fi

# be sure to set the owner of the custom app settings directory
[ -e "$HOME/$APPS_BASEDIR" ] && chown -R $USER $HOME/$APPS_BASEDIR

# quit if script is invoked by template user himself
[ "$USER" = "$TEMPLATE_USER" ] && exit 0

# iterate over profile directories and copy them to users home
for i in $PROFILE_DIRS; do
	[ -e "$HOME/$i" ] && rm -rf $HOME/$i
	[ -e "$PROFILE_HOME/$i" ] && cp -a $PROFILE_HOME/$i $HOME
	[ -e "$HOME/$i" ] && chown -R $USER $HOME/$i
done

# finally sets permissions for $STUDENTSHOME
if ! check_empty_dir $STUDENTSHOME; then
	chown $ADMINISTRATOR:$TEACHERSGROUP $STUDENTSHOME/*
	chmod 1751 $STUDENTSHOME/*
fi

