#!/bin/sh
# logout script for linuxmuster
# invoked by pammount
# schmitt@lmz-bw.de
#

# parameters given by pammount
USER=$1
MNTPT=$2

# exit if no parameters are set
[[ -z "$USER" || -z "$MNTPT" ]] && exit 1

# fetch user's home
HOME=`echo $MNTPT | grep /home | grep /${USER}`

if [ -n "$HOME" ]; then

    # user's temporary dirs
    KDEHOME=/tmp/.kde_${USER}
    DESKTOP=/tmp/Desktop_${USER}

    # creating necessary dirs in user's home
    for i in $HOME/.kde $HOME/.kde/Autostart $HOME/.kde/share $HOME/Desktop; do
	[[ -L "$i" || -f "$i" ]] && rm $i
	[ -d "$i" ] || mkdir -p $i
	chown $USER $i
	chmod 700 $i
    done

    # syncing user's kde settings
    [ -d "$KDEHOME/share" ] && rsync -a --delete $KDEHOME/share/ $HOME/.kde/share/

    # syncing user's kde Autostart
    [ -d "$KDEHOME/Autostart" ] && rsync -a --delete $KDEHOME/Autostart/ $HOME/.kde/Autostart/

    # syncing user's desktop
    [ -d "$DESKTOP" ] && rsync -a --delete $DESKTOP/ $HOME/Desktop/

fi

# umount
umount $MNTPT
status=$?

# if unmounting fails kill processes which prevent $MNTPT from unmounting
# and do a second try
if [ "$status" -ne 0 ]; then

    sleep 5
    for i in `lsof | grep $MNTPT | awk '{ print $2 }'`; do
	kill $i
    done
    umount $MNTPT
    status=$?

fi

# exit with umount status
exit $status
