#!/bin/sh

# 11.07.2009

# Source debconf library.
. /usr/share/debconf/confmodule

# source config
[ -e /etc/linuxmuster-client.conf ] && . /etc/linuxmuster-client.conf

db_version 2.0
db_capb backup

PRIORITY="critical"

db_title "linuxmuster-client Konfiguration"

# ldap server uri
while [ -z "$INPUT" ]; do
  db_input $PRIORITY shared/ldapns/ldap-server || true
  db_go
  db_get shared/ldapns/ldap-server || true
  INPUT=$RET
done

# ldap basedn
unset INPUT
while [ -z "$INPUT" ]; do
  db_input $PRIORITY shared/ldapns/base-dn || true
  db_go
  db_get shared/ldapns/base-dn || true
  INPUT=$RET
done

# template user
db_set linuxmuster-client/template_user $TEMPLATE_USER || true
db_input $PRIORITY linuxmuster-client/template_user || true
db_go

# firefox
if [ "$FIREFOX" = "yes" ]; then
	db_set linuxmuster-client/firefox true || true
else
	db_set linuxmuster-client/firefox false || true
fi
db_input $PRIORITY linuxmuster-client/firefox || true
db_go

# finish debconf stuff
db_stop

