#!/bin/bash
#
# linuxmuster debian client configuration script
#
# schmitt@lmz-bw.de
#

# read default variables
. /usr/share/linuxmuster-client/config || exit 1

# read hostname
clientname=`cat /etc/hostname`

check_mountpoints() {

	echo -n "linuxmuster-client: checking mountpoints"
		
	# administrators homes
	[ -d "$ADMINSHOME" ] || mkdir -p $ADMINSHOME
	chown root:root $ADMINSHOME
	chmod 771 $ADMINSHOME
		
	# teachers homes
	[ -d "$TEACHERSHOME" ] || mkdir -p $TEACHERSHOME
	chown $ADMINISTRATOR:$TEACHERSGROUP $TEACHERSHOME
	chmod 751 $TEACHERSHOME
		
	# students homes
	[ -d "$STUDENTSHOME" ] || mkdir -p $STUDENTSHOME
	chown root:root $STUDENTSHOME
	chmod 775 $STUDENTSHOME
		
	# workstations homes
	[ -d "$WSHOME" ] || mkdir -p $WSHOME
	chown root:root $WSHOME
	chmod 775 $WSHOME
		
	# attic
	[ -d "$ATTICHOME" ] || mkdir -p $ATTICHOME
	chown root:root $ATTICHOME
	chmod 775 $ATTICHOME
		
	# shares
	[ -d "$SHAREHOME" ] || mkdir -p $SHAREHOME
	chown root:$DOMADMINS $SHAREHOME
	chmod 771 $SHAREHOME
		
	# tasks
	[ -d "$TASKSCACHE" ] || mkdir -p $TASKSCACHE
	chown root:root $TASKSCACHE
	chmod 1771 $TASKSCACHE
		
	# access to backup folder, only for administrator
	[ -d "$BACKUPMNTPOINT" ] || mkdir -p $BACKUPMNTPOINT
	chown root:root $BACKUPMNTPOINT
	chmod 755 $BACKUPMNTPOINT

	echo .

} # check_mountpoints


cleaning_homes() {

	echo -n "linuxmuster-client: cleaning homes ..."

	for i in $ADMINSHOME $TEACHERSHOME $WSHOME $STUDENTSHOME $SHAREHOME $ATTICHOME; do

		if ! grep -q $i /etc/mtab; then
			rm -rf $i/* &> /dev/null
		fi

	done

	echo .

} # cleaning_homes


restore_xorg() {

	if [ -f /etc/X11/xorg.conf.default ]; then
		echo -n "linuxmuster-client: restoring default xorg.conf"
		mv /etc/X11/xorg.conf.default /etc/X11/xorg.conf
		echo .
	fi

}


case $1 in
	
	start)
		check_mountpoints
		cleaning_homes
		;;

	stop)
		cleaning_homes
		restore_xorg
		;;

	*)
		;;

esac

exit 0
