#!/bin/bash

### BEGIN INIT INFO
# Provides:          linuxmuster-client
# Required-Start:
# Required-Stop:
# Default-Start:
# Default-Stop:
# Short-Description: Updates hostname and xorg.conf
# Description:       linuxmuster debian client configuration script
### END INIT INFO

# read default variables
. /usr/share/linuxmuster-client/config || exit 1
. /etc/linuxmuster-client.conf || exit 1

# read hostname
clientname=`cat /etc/hostname`

check_mountpoints() {

	echo -n "linuxmuster-client: checking mountpoints"
		
	# administrators homes
	[ -d "$ADMINSHOME" ] || mkdir -p $ADMINSHOME
	chown root:root $ADMINSHOME
	chmod 771 $ADMINSHOME
		
	# teachers homes
	[ -d "$TEACHERSHOME" ] || mkdir -p $TEACHERSHOME
	chown $ADMINISTRATOR:$TEACHERSGROUP $TEACHERSHOME
	chmod 751 $TEACHERSHOME
		
	# students homes
	[ -d "$STUDENTSHOME" ] || mkdir -p $STUDENTSHOME
	chown root:root $STUDENTSHOME
	chmod 775 $STUDENTSHOME
		
	# workstations homes
	[ -d "$WSHOME" ] || mkdir -p $WSHOME
	chown root:root $WSHOME
	chmod 775 $WSHOME
		
	# attic
	[ -d "$ATTICHOME" ] || mkdir -p $ATTICHOME
	chown root:root $ATTICHOME
	chmod 775 $ATTICHOME
		
	# shares
	[ -d "$SHAREHOME" ] || mkdir -p $SHAREHOME
	chown root:$DOMADMINS $SHAREHOME
	chmod 771 $SHAREHOME
		
	# progs & cdrom
	[ -d "$PROGSDIR" ] || mkdir -p $PROGSDIR
	[ -d "$CDSDIR" ] || mkdir -p $CDSDIR
	chown $ADMINISTRATOR:$DOMADMINS $SAMBAHOME/*
	chmod 775 $SAMBAHOME/*
	
	# tasks
	[ -d "$TASKSCACHE" ] || mkdir -p $TASKSCACHE
	chown root:root $SOPHOMORIXCACHE
	chmod 755 $SOPHOMORIXCACHE
	chown root:root $TASKSCACHE
	chmod 1771 $TASKSCACHE
		
	# access to backup folder, only for administrator
	[ -d "$BACKUPMNTPOINT" ] || mkdir -p $BACKUPMNTPOINT
	chown root:root $BACKUPMNTPOINT
	chmod 755 $BACKUPMNTPOINT

	echo .

} # check_mountpoints


cleaning_homes() {

	echo -n "linuxmuster-client: cleaning homes ..."

	for i in $ADMINSHOME $TEACHERSHOME $WSHOME $STUDENTSHOME $SHAREHOME $ATTICHOME $SAMBAHOME; do

		if ! grep -q $i /etc/mtab; then
			[ -d "$i" ] && rm -rf $i/* &> /dev/null
		fi

	done

	# cleaning previous user from kdm
	[ -e /var/lib/kdm/kdmsts ] && rm -rf /var/lib/kdm/kdmsts

	echo .

} # cleaning_homes

copy_xorg() {

	# copy host specific xorg.conf
	if [ -s "/etc/X11/xorg.conf.$clientname" ]; then
		echo -n " * linuxmuster-client: setting up xorg.conf for $clientname"
		if [ -L /etc/X11/xorg.conf ]; then
			rm /etc/X11/xorg.conf
		else
			cp /etc/X11/xorg.conf /etc/X11/xorg.conf.default
		fi
		cp /etc/X11/xorg.conf.$clientname /etc/X11/xorg.conf
		echo .
	fi

}

restore_xorg() {

	if [ -s /etc/X11/xorg.conf.default ]; then
		echo -n "linuxmuster-client: restoring default xorg.conf"
		mv /etc/X11/xorg.conf.default /etc/X11/xorg.conf
		echo .
	fi

}


case $1 in
	
	start)
		cleaning_homes
		check_mountpoints
		copy_xorg
		;;

	stop)
		cleaning_homes
		restore_xorg
		;;

	*)
		;;

esac

exit 0

