#!/bin/bash

### BEGIN INIT INFO
# Provides:          linuxmuster-hostname
# Required-Start:
# Required-Stop:
# Default-Start:
# Default-Stop:
# Short-Description: writes hostname in dhclient config
# Description:       linuxmuster debian client configuration script
### END INIT INFO

# Thomas Schmitt <schmitt@lmz-bw.de>
# 11.07.2009
#

# read hostname
clientname=`cat /etc/hostname`
[ -z "$clientname" ] && exit 0

DHCLIENTCONF=/etc/dhcp3/dhclient.conf

case $1 in

	start)
		if [ -e "$DHCLIENTCONF" ]; then
			# backup original dhclient.conf
			[ -e "$DHCLIENTCONF.dist" ] || cp $DHCLIENTCONF $DHCLIENTCONF.dist

			# patch dhclient.conf with hostname
			echo -n " * linuxmuster-client: setting up dhcp hostname for $clientname"
			if grep -q "^send host-name" $DHCLIENTCONF; then
				sed -e "s/^send host-name.*/send host-name \"$clientname\";/" -i $DHCLIENTCONF
			else
				echo "send host-name \"$clientname\";" >> $DHCLIENTCONF
			fi
			echo .
		fi
		;;

	*)
		;;

esac

exit 0
