#! /bin/bash
# postinst script for linuxmuster
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package
#

# read debconf stuff
. /usr/share/debconf/confmodule

case "$1" in

	configure)

		# read default variables
		. /usr/share/linuxmuster-client/config || exit 1
		. /usr/share/linuxmuster-client/supported_distros || exit 1

		# check the distribution and do specific stuff
		binpath=bin
		cups=cupsys
		if grep -q "$karmic" /etc/issue; then
			echo "This is $karmic!"
			distro=karmic
			cups=cups
		elif grep -q "$jaunty" /etc/issue; then
			echo "This is $jaunty!"
			distro=jaunty
			cups=cups
		elif grep -q "$intrepid" /etc/issue; then
			echo "This is $intrepid!"
			distro=intrepid
			cups=cups
		elif grep -q "$hardy" /etc/issue; then
			echo "This is $hardy!"
			distro=hardy
		else
			echo "This distribution is not supported!"
			exit 1
		fi

		# sets hostname for dhclient at boot time
		update-rc.d linuxmuster-hostname start 40 S .

		# adding system groups plugdev and nvram
		for i in plugdev nvram; do
			if ! grep -q ^${i}: /etc/group; then
				addgroup --system $i
			fi
		done

		# adding administrator to sudoers
		if [ -e /etc/sudoers ]; then
			if ! grep -q ^$ADMINISTRATOR /etc/sudoers; then
				echo "Adding $ADMINISTRATOR to sudoers ..."
				echo >> /etc/sudoers
				echo "# linuxmuster: $ADMINISTRATOR may gain root privileges" >> /etc/sudoers
				echo "$ADMINISTRATOR ALL=(ALL) ALL" >> /etc/sudoers
			fi
		fi

		# adding cupsys user to shadow group
		if id cupsys &> /dev/null; then
			if ! id cupsys | grep -qw shadow; then
				addgroup cupsys shadow
			fi
		fi

		# adding printoperators group to cups system groups
		if grep -q ^SystemGroup /etc/cups/cupsd.conf; then
			if ! grep ^SystemGroup /etc/cups/cupsd.conf | grep -q $PRINTERADMINS; then
				echo "Adding group $PRINTERADMINS to cupsd system groups ..."
				cp /etc/cups/cupsd.conf /etc/cups/cupsd.conf.dpkg-old
				sed -e "s/^SystemGroup.*/SystemGroup lpadmin $PRINTERADMINS/" /etc/cups/cupsd.conf.dpkg-old > /etc/cups/cupsd.conf
				/etc/init.d/$cups restart
			fi
		fi

  # configure package
  . /usr/share/linuxmuster-client/configure

		# basedn
		db_get shared/ldapns/ldap-server || true
		serverip=$RET
		if [ -z "$serverip" ]; then
			echo "Cannot get the ip for the ldap server! Skipping configuration!"
			exit 0
		fi

  # serverip
		db_get shared/ldapns/base-dn || true
		basedn=$RET
		if [ -z "$basedn" ]; then
			echo "Cannot get ldap basedn! Skipping configuration!"
			exit 0
		fi

  # template user
  db_get linuxmuster-client/template_user || true
  template_user=$RET

  # firefox profile from template user?
  db_get linuxmuster-client/firefox || true
  if $RET; then firefox=yes; else firefox=no; fi

  # my files folder
  db_get linuxmuster-client/myfiles || true
  myfiles="$RET"

  # apps base dir
  db_get linuxmuster-client/apps_basedir || true
  apps_basedir="$RET"

		# patching configuration files
		echo "Patching configuration ..."
		cd /var/lib/linuxmuster-client
		for i in common $distro; do
			cd $i/templates
			find -type f | xargs -i -t sh -c \
			"sed -e 's%@@studentshome@@%${STUDENTSHOME}%g
		 					s%@@sharehome@@%${SHAREHOME}%g
		 					s%@@progsdir@@%${PROGSDIR}%g
		 					s%@@cdsdir@@%${CDSDIR}%g
		 					s%@@taskscache@@%${TASKSCACHE}%g
		 					s%@@backupmntpoint@@%${BACKUPMNTPOINT}%g
		 					s%@@basedn@@%${basedn}%g
		 					s%@@binpath@@%${binpath}%g
		 					s%@@administrator@@%${ADMINISTRATOR}%g
		 					s%@@pgmadmin@@%${PGMADMIN}%g
		 					s%@@serverip@@%${serverip}%g' {} > /{}" 2> /dev/null 1> /dev/null
			cd ../../
		done

  # patch package configfile
	 [ -e /etc/linuxmuster-client/config ] && cp /etc/linuxmuster-client/config /etc/linuxmuster-client/config.dpkg-old
	 if grep -q ^TEMPLATE_USER /etc/linuxmuster-client/config; then
		 sed -e "s|^TEMPLATE_USER=.*|TEMPLATE_USER=$template_user|" -i /etc/linuxmuster-client/config
	 else
		 echo "TEMPLATE_USER=$template_user" > /etc/linuxmuster-client/config
	 fi
 	if grep -q ^FIREFOX /etc/linuxmuster-client/config; then
		 sed -e "s|^FIREFOX=.*|FIREFOX=$firefox|" -i /etc/linuxmuster-client/config
	 else
		 echo "FIREFOX=$firefox" >> /etc/linuxmuster-client/config
 	fi
	 if grep -q ^MYFILES /etc/linuxmuster-client/config; then
		 sed -e "s|^MYFILES=.*|MYFILES=\"$myfiles\"|" -i /etc/linuxmuster-client/config
	 else
		 echo "MYFILES=\"$myfiles\"" > /etc/linuxmuster-client/config
	 fi
	 if grep -q ^APPS_BASEDIR /etc/linuxmuster-client/config; then
		 sed -e "s|^APPS_BASEDIR=.*|APPS_BASEDIR=\"$apps_basedir\"|" -i /etc/linuxmuster-client/config
	 else
		 echo "APPS_BASEDIR=\"$apps_basedir\"" > /etc/linuxmuster-client/config
	 fi

		# remove hal's obsolete mountpolicies
		if [ -e /etc/hal/fdi/policy/mountpolicies.fdi ]; then
			mv /etc/hal/fdi/policy/mountpolicies.fdi /etc/hal/fdi/policy/mountpolicies.fdi.dpkg-old
			[ -e /etc/init.d/dbus ] && /etc/init.d/dbus restart
		fi

		# remove ivman from Xsession.options
		if [ -s /etc/X11/Xsession.options ]; then
			if grep -q use-session-ivman /etc/X11/Xsession.options; then
				cp /etc/X11/Xsession.options /etc/X11/Xsession.options.dpkg-old
				grep -v use-session-ivman /etc/X11/Xsession.options.dpkg-old > /etc/X11/Xsession.options
			fi
		fi

		# remove ivman's default
		[ -e /etc/default/ivman ] && mv /etc/default/ivman /etc/default/ivman.dpkg-old

		# remove ivman script from dapper
		[ -e /etc/X11/ivman-xsession ] && mv /etc/X11/ivman-xsession /etc/X11/ivman-xsession.dpkg-old

		echo "Note: You have to reboot the client if you have installed the package for the first time!"

		;;

	abort-upgrade|abort-remove|abort-deconfigure)

		;;

	*)

		echo "postinst called with unknown argument \`$1'" >&2
		exit 1

		;;

esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

db_stop

exit 0

